[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:lightremote]
command=/usr/local/bin/lightremote --bind 0.0.0.0 --port 8080 --root / --data-dir /data/lightremote
directory=/data/projects
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/lightremote.err.log
stdout_logfile=/var/log/supervisor/lightremote.out.log
environment=HOME="/data/lightremote"

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile=/var/log/supervisor/nginx.out.log

[program:cloudflared]
command=/bin/bash -c 'cloudflared tunnel --no-autoupdate run --token $CF_TOKEN'
autostart=false
autorestart=true
stderr_logfile=/var/log/supervisor/cloudflared.err.log
stdout_logfile=/var/log/supervisor/cloudflared.out.log
